//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Resource {
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    Assembly assembly = Assembly.GetEntryAssembly();
                    var attribute = assembly.GetCustomAttribute<AssemblyCompanyAttribute>();
                    string companyName = attribute.Company;
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
                        companyName + ".Model.Resource.extern_resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意事项：.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.本服务仅支持windows操作系统；
        ///2.如果服务器上开启了防火墙，需要在防火墙中设置允许本服务访问网络，否则可能会导致客户端无法正常连接本服务；
        ///3.如果客户端是silverlight版，则本服务的端口需要在4502到4534之间；
        ///4.如果客户端是silverlight版，则需搭配策略服务使用，否则客户端将无法连接本服务。.
        /// </summary>
        internal static string AttentionCommonDetail {
            get {
                return ResourceManager.GetString("AttentionCommonDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.运行本服务时需要提供正确的许可文件lic.lic，否则将无法启动本服务；.
        /// </summary>
        internal static string AttentionLicenseDetail {
            get {
                return ResourceManager.GetString("AttentionLicenseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    授权点数   .
        /// </summary>
        internal static string AuthorityCount {
            get {
                return ResourceManager.GetString("AuthorityCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 授权不正确！.
        /// </summary>
        internal static string AuthorityNotRight {
            get {
                return ResourceManager.GetString("AuthorityNotRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本服务负责给客户端提供授权,任何客户端在正常使用之前都需取得对应的授权.
        /// </summary>
        internal static string AuthorityServiceDescription {
            get {
                return ResourceManager.GetString("AuthorityServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACS-授权服务.
        /// </summary>
        internal static string AuthorityServiceTitle {
            get {
                return ResourceManager.GetString("AuthorityServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 负载均衡读取配置文件失败，请关闭程序后检查配置文件是否存在或配置是否正确，确认正确后再重启程序！错误原因：.
        /// </summary>
        internal static string BalanceServiceConfigReadFail {
            get {
                return ResourceManager.GetString("BalanceServiceConfigReadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通过一定的调度算法向终端提供可用的PDV服务，以便终端总是可以使用某一个PDV服务.
        /// </summary>
        internal static string BalanceServiceDescription {
            get {
                return ResourceManager.GetString("BalanceServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACS-负载均衡服务.
        /// </summary>
        internal static string BalanceServiceTitle {
            get {
                return ResourceManager.GetString("BalanceServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到可用的PDV服务.
        /// </summary>
        internal static string CannotFindAvailablePDV {
            get {
                return ResourceManager.GetString("CannotFindAvailablePDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法打开日志文件.
        /// </summary>
        internal static string CannotOpenLogFile {
            get {
                return ResourceManager.GetString("CannotOpenLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击服务重启按钮.
        /// </summary>
        internal static string ClickServiceRestartButton {
            get {
                return ResourceManager.GetString("ClickServiceRestartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户端连接超时.
        /// </summary>
        internal static string ClientLinkTimeOut {
            get {
                return ResourceManager.GetString("ClientLinkTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置文件加载失败.
        /// </summary>
        internal static string ConfigLoadFail {
            get {
                return ResourceManager.GetString("ConfigLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理所有客户端的配置,给客户端提供获取和保存配置的功能.
        /// </summary>
        internal static string ConfigServiceDescription {
            get {
                return ResourceManager.GetString("ConfigServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACS-配置服务.
        /// </summary>
        internal static string ConfigServiceTitle {
            get {
                return ResourceManager.GetString("ConfigServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建policy响应线程时发生异常:.
        /// </summary>
        internal static string CreatePoliceResponseThreadException {
            get {
                return ResourceManager.GetString("CreatePoliceResponseThreadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建扫描定时器时发生异常:.
        /// </summary>
        internal static string CreateScanTimerException {
            get {
                return ResourceManager.GetString("CreateScanTimerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建状态报告线程时发生异常:.
        /// </summary>
        internal static string CreateStateThreadException {
            get {
                return ResourceManager.GetString("CreateStateThreadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试用版.
        /// </summary>
        internal static string DemoVersion {
            get {
                return ResourceManager.GetString("DemoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 域名.
        /// </summary>
        internal static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .本服务是基于.net framework4.0的，所以需要在运行的主机上安装.net framework.
        /// </summary>
        internal static string DotNetLimit {
            get {
                return ResourceManager.GetString("DotNetLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进入监听状态.
        /// </summary>
        internal static string EnterListenState {
            get {
                return ResourceManager.GetString("EnterListenState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 异常类型:{0}
        ///异常消息:{1}
        ///异常信息:{2}
        ///.
        /// </summary>
        internal static string ExceptionDetail {
            get {
                return ResourceManager.GetString("ExceptionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 处理policy请求时发生异常:.
        /// </summary>
        internal static string ExceptionWhenHandlePolicy {
            get {
                return ResourceManager.GetString("ExceptionWhenHandlePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行状态报告线程时发生异常:.
        /// </summary>
        internal static string ExcuteStateThreadException {
            get {
                return ResourceManager.GetString("ExcuteStateThreadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正常退出程序.
        /// </summary>
        internal static string ExitProcessNormal {
            get {
                return ResourceManager.GetString("ExitProcessNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 截止时间  .
        /// </summary>
        internal static string ExpiredTime {
            get {
                return ResourceManager.GetString("ExpiredTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .如果服务器上开启了防火墙，需要在防火墙中设置允许本服务访问网络，否则可能会导致终端无法正常连接本服务;.
        /// </summary>
        internal static string Firewall {
            get {
                return ResourceManager.GetString("Firewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 功能说明：.
        /// </summary>
        internal static string FunctionDescription {
            get {
                return ResourceManager.GetString("FunctionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string languageSpace {
            get {
                return ResourceManager.GetString("languageSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志文件打开失败.
        /// </summary>
        internal static string LogFileOpenFail {
            get {
                return ResourceManager.GetString("LogFileOpenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志服务器地址.
        /// </summary>
        internal static string LogServiceAddress {
            get {
                return ResourceManager.GetString("LogServiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本服务接收并保存来自终端、缓存服务及更新客户端的日志.
        /// </summary>
        internal static string LogServiceDescription {
            get {
                return ResourceManager.GetString("LogServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志服务器端口.
        /// </summary>
        internal static string LogServicePort {
            get {
                return ResourceManager.GetString("LogServicePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACS-日志服务.
        /// </summary>
        internal static string LogServiceTitle {
            get {
                return ResourceManager.GetString("LogServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本服务负责监控指定的进程，如果进程没有启动则自动启动被监控进程，如果进程已经停止了响应将重启被监控的进程。.
        /// </summary>
        internal static string MonitorServiceDescription {
            get {
                return ResourceManager.GetString("MonitorServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监控服务启动完成.
        /// </summary>
        internal static string MonitorServiceFinishStart {
            get {
                return ResourceManager.GetString("MonitorServiceFinishStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .需要增减被监控的进程，则请修改配置文件MonitorService_config.xml；.
        /// </summary>
        internal static string MonitorServiceProcessHandle {
            get {
                return ResourceManager.GetString("MonitorServiceProcessHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .修改本服务的配置文件MonitorService_config.xml后需要重启本服务才会让新的配置生效。.
        /// </summary>
        internal static string MonitorServiceTakeAffectWarning {
            get {
                return ResourceManager.GetString("MonitorServiceTakeAffectWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACS-进程监控服务.
        /// </summary>
        internal static string MonitorServiceTitle {
            get {
                return ResourceManager.GetString("MonitorServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完全版.
        /// </summary>
        internal static string NormalVersion {
            get {
                return ResourceManager.GetString("NormalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .开启了本服务之后，不要手动启动PDV服务，否则无法完成监控。.
        /// </summary>
        internal static string NotStartPDVManually {
            get {
                return ResourceManager.GetString("NotStartPDVManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持的配置项，请确认拼写是否正确！.
        /// </summary>
        internal static string NotSupportConfig {
            get {
                return ResourceManager.GetString("NotSupportConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .本服务仅能在windows操作系统上正常使用；.
        /// </summary>
        internal static string OnlyRunOnWindows {
            get {
                return ResourceManager.GetString("OnlyRunOnWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解析配置文件错误:.
        /// </summary>
        internal static string ParseConfigError {
            get {
                return ResourceManager.GetString("ParseConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 路径.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 策略服务启动完成.
        /// </summary>
        internal static string PolicyProcessStartFinish {
            get {
                return ResourceManager.GetString("PolicyProcessStartFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 的策略请求.
        /// </summary>
        internal static string PolicyRequest {
            get {
                return ResourceManager.GetString("PolicyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本服务供使用silver light开发的客户端在于服务器进行业务通信时获取策略描述用.
        /// </summary>
        internal static string PolicyServiceDescription {
            get {
                return ResourceManager.GetString("PolicyServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACS-策略服务.
        /// </summary>
        internal static string PolicyServiceTitle {
            get {
                return ResourceManager.GetString("PolicyServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4, 端口必须大于.
        /// </summary>
        internal static string PortMustBiggerThan {
            get {
                return ResourceManager.GetString("PortMustBiggerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置文件读取失败，请关闭程序后检查配置文件是否存在或配置是否正确，确认正确后再重启程序！错误原因：.
        /// </summary>
        internal static string ReadConfigFileFail {
            get {
                return ResourceManager.GetString("ReadConfigFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1, 接收日志服务查询,为终端提供日志服务器的地址和端口.
        /// </summary>
        internal static string ReceiveLogSeviceQuery {
            get {
                return ResourceManager.GetString("ReceiveLogSeviceQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收到一个来自:.
        /// </summary>
        internal static string ReceiveOneRequestFrom {
            get {
                return ResourceManager.GetString("ReceiveOneRequestFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2, 接收升级查询,为终端提供升级包地址和访问授权信息.
        /// </summary>
        internal static string ReceiveUpdateQuery {
            get {
                return ResourceManager.GetString("ReceiveUpdateQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定时重启对象创建完毕.
        /// </summary>
        internal static string RestartObjectCreateFinish {
            get {
                return ResourceManager.GetString("RestartObjectCreateFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5, 更改配置后必须重启服务才能生效.
        /// </summary>
        internal static string RestartServiceToTakeAffect {
            get {
                return ResourceManager.GetString("RestartServiceToTakeAffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描对象创建完毕.
        /// </summary>
        internal static string ScanObjectCreateFinish {
            get {
                return ResourceManager.GetString("ScanObjectCreateFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 往负载均衡服务器发送数据时发生异常:.
        /// </summary>
        internal static string SendDataToBalanceException {
            get {
                return ResourceManager.GetString("SendDataToBalanceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务出错,等待重启.
        /// </summary>
        internal static string ServiceErrorPleaseRestart {
            get {
                return ResourceManager.GetString("ServiceErrorPleaseRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .负责启动PDV服务和监控PDV服务运行状态，如果PDV出现死机，则自动重启PDV服务；.
        /// </summary>
        internal static string ServiceProxyFunctionDetail1 {
            get {
                return ResourceManager.GetString("ServiceProxyFunctionDetail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .向负载均衡服务报告PDV服务的状态变化。.
        /// </summary>
        internal static string ServiceProxyFunctionDetail2 {
            get {
                return ResourceManager.GetString("ServiceProxyFunctionDetail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACS-服务代理.
        /// </summary>
        internal static string ServiceProxyTitle {
            get {
                return ResourceManager.GetString("ServiceProxyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .要想使用本服务，必须保证本服务在服务代理服务前启动.
        /// </summary>
        internal static string ServiceRunBeforServiceProxy {
            get {
                return ResourceManager.GetString("ServiceRunBeforServiceProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .本服务需要和PDV服务运行在同一台物理服务器上；.
        /// </summary>
        internal static string ServiceRunWithPDV {
            get {
                return ResourceManager.GetString("ServiceRunWithPDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务停止.
        /// </summary>
        internal static string ServiceStop {
            get {
                return ResourceManager.GetString("ServiceStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .本服务需要配合服务代理使用；.
        /// </summary>
        internal static string ServiceUseWithServiceProxy {
            get {
                return ResourceManager.GetString("ServiceUseWithServiceProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .如果客户端是silverlight版，则本服务的端口需要在4502到4534之间；.
        /// </summary>
        internal static string SilverlightPortLimit {
            get {
                return ResourceManager.GetString("SilverlightPortLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .如果客户端是silverlight版，则需搭配策略服务使用，否则客户端将无法连接本服务。.
        /// </summary>
        internal static string SilverlightWithPolice {
            get {
                return ResourceManager.GetString("SilverlightWithPolice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application unhandledException:{0};
        ///堆栈信息:{1}.
        /// </summary>
        internal static string StackInfo {
            get {
                return ResourceManager.GetString("StackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始监听来自客户端的策略请求.
        /// </summary>
        internal static string StartMonitorClientPoliceRequest {
            get {
                return ResourceManager.GetString("StartMonitorClientPoliceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始运行.
        /// </summary>
        internal static string StartRun {
            get {
                return ResourceManager.GetString("StartRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动服务线程异常.
        /// </summary>
        internal static string StartServiceTheadException {
            get {
                return ResourceManager.GetString("StartServiceTheadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止服务线程异常.
        /// </summary>
        internal static string StopServiceTheadException {
            get {
                return ResourceManager.GetString("StopServiceTheadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用程序线程错误:{0}.
        /// </summary>
        internal static string ThreadError {
            get {
                return ResourceManager.GetString("ThreadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 心跳检测对象创建完毕.
        /// </summary>
        internal static string TigerObjectCreateFinish {
            get {
                return ResourceManager.GetString("TigerObjectCreateFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出现应用程序未处理UI异常:.
        /// </summary>
        internal static string UIUnhandleExceptionOccur {
            get {
                return ResourceManager.GetString("UIUnhandleExceptionOccur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出现应用程序未处理非UI异常:.
        /// </summary>
        internal static string UnhandleExceptionOccur {
            get {
                return ResourceManager.GetString("UnhandleExceptionOccur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 为所有终端提供升级服务.
        /// </summary>
        internal static string UpdateForAllClients {
            get {
                return ResourceManager.GetString("UpdateForAllClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 升级服务监听端口.
        /// </summary>
        internal static string UpdateListenPort {
            get {
                return ResourceManager.GetString("UpdateListenPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1, 升级服务监听端口设置必须大于.
        /// </summary>
        internal static string UpdateListenPortBiggerThan {
            get {
                return ResourceManager.GetString("UpdateListenPortBiggerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2, 升级包路径需要设置为共享目录下的路径.
        /// </summary>
        internal static string UpdatePackagePathSet {
            get {
                return ResourceManager.GetString("UpdatePackagePathSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3, 如果共享升级包所在服务器没加入域，域名应该填写服务器的IP地址.
        /// </summary>
        internal static string UpdateServiceDemainAddress {
            get {
                return ResourceManager.GetString("UpdateServiceDemainAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACS-升级服务.
        /// </summary>
        internal static string UpdateServiceTitle {
            get {
                return ResourceManager.GetString("UpdateServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        internal static string UpdateServiceTitleLinkString {
            get {
                return ResourceManager.GetString("UpdateServiceTitleLinkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
